package com.zestful.controller;

import com.zestful.model.CustomRecipe;
import com.zestful.model.MealPlan;
import com.zestful.payload.CustomRecipeDTO;
import com.zestful.payload.MealPlanDTO;
import com.zestful.payload.ai.AiMealPlanItem;
import com.zestful.service.AiService;
import com.zestful.service.CustomRecipeService;
import com.zestful.service.MealPlanService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/mealplan")
public class MealPlanController {

    private final MealPlanService mealPlanService;
    private final CustomRecipeService customRecipeService;
    private final AiService aiService;

    public MealPlanController(MealPlanService mealPlanService, CustomRecipeService customRecipeService, AiService aiService) {
        this.mealPlanService = mealPlanService;
        this.customRecipeService = customRecipeService;
        this.aiService = aiService;
    }

    @GetMapping
    public ResponseEntity<List<MealPlan>> getMyMealPlan(Principal principal) {
        return ResponseEntity.ok(mealPlanService.getMealPlan(principal.getName()));
    }

    @PostMapping
    public ResponseEntity<MealPlan> saveMeal(@RequestBody MealPlanDTO dto, Principal principal) {
        return new ResponseEntity<>(mealPlanService.saveMeal(dto, principal.getName()), HttpStatus.CREATED);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteMeal(@PathVariable Long id, Principal principal) {
        mealPlanService.deleteMeal(id, principal.getName());
        return ResponseEntity.ok().build();
    }

    @PostMapping("/generate")
    public ResponseEntity<?> generateAiPlan(@RequestBody Map<String, String> preferences, Principal principal) {
        String userEmail = principal.getName();
        
        List<AiMealPlanItem> aiPlan = aiService.generateMealPlan(
            preferences.get("diet"), 
            preferences.get("health")
        );

        if (aiPlan.isEmpty()) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("AI could not generate a plan.");
        }

        for (AiMealPlanItem item : aiPlan) {
            CustomRecipeDTO recipeDTO = new CustomRecipeDTO();
            recipeDTO.setTitle(item.getSuggestion());
            recipeDTO.setInstructions("Auto-generated by AI. Check online for details.");
            recipeDTO.setImageUrl("https://via.placeholder.com/300?text=AI+Meal");
            recipeDTO.setIngredients(new ArrayList<>()); 

            try {
                CustomRecipe savedRecipe = customRecipeService.createRecipe(recipeDTO, userEmail);

                MealPlanDTO planDTO = new MealPlanDTO();
                planDTO.setDayOfWeek(item.getDay());
                planDTO.setMealType(item.getMealType());
                planDTO.setCustomRecipeId(savedRecipe.getId());
                
                mealPlanService.saveMeal(planDTO, userEmail);
            } catch (Exception e) {
                System.err.println("Error saving AI meal: " + e.getMessage());
            }
        }

        return ResponseEntity.ok().build();
    }
}